### ISSUE TITLE
esc doesn't work to close ; filter button not shown

### ISSUE THREAD

**Issue by dogvetusa** [ketho-wow/GuildBankSearch#1]
loaded only guild bank search to check for problems between addons but even with only GBS loaded the escape key would not close the guild pane.
Was still able to click in the search field where the filter button is normally located and type but the filter button is gone and the esc key doesn't work when the guild bank pane is open.

wow version: 9.2.0.43340
addon version: default curseforge install from 10-1-21

**Comment by Ketho** [comment]
Hm I will look at it in the weekend

**Comment by Ketho** [comment]
Sorry for the delay.
It should be fixed now in [9.2.0](https://github.com/ketho-wow/GuildBankSearch/releases/tag/9.2.0.0), it was apparently broken since patch 9.1.5

**Comment by dogvetusa** [comment]
did check this after the posting, working good 👍
